# Generated by Django 4.1.3 on 2022-11-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lorem ipsum', max_length=20)),
                ('summary', models.CharField(default='Lorem ipsum', max_length=40)),
                ('category', models.CharField(default='Lorem ipsum', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, max_length=2)),
                ('instructor', models.CharField(default='Lorem ipsum', max_length=20)),
                ('last_update', models.DateField(default=1984)),
                ('language', models.CharField(default='Lorem ipsum', max_length=20)),
                ('subtitle', models.CharField(default='Lorem ipsum', max_length=20)),
                ('price', models.IntegerField(default=199)),
                ('description', models.CharField(default='Lorem ipsum', max_length=200)),
                ('overview', models.CharField(default='Lorem ipsum', max_length=200)),
            ],
        ),
    ]
