# Generated by Django 4.1.3 on 2023-01-08 00:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(default='avatar.png', upload_to='images\\instructors')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews', models.IntegerField(default=100)),
                ('students', models.IntegerField(default=1000)),
                ('summary', models.CharField(default='Lorem ipsum', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lorem ipsum', max_length=200)),
                ('summary', models.CharField(default='Lorem ipsum', max_length=400)),
                ('category', models.CharField(default='Lorem ipsum', max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('last_update', models.DateField(default=1984)),
                ('language', models.CharField(default='Lorem ipsum', max_length=200)),
                ('subtitle', models.CharField(default='Lorem ipsum', max_length=200)),
                ('price', models.IntegerField(default=199)),
                ('description', models.CharField(default='Lorem ipsum', max_length=600)),
                ('overview', models.CharField(default='Lorem ipsum', max_length=600)),
                ('instructors', models.ManyToManyField(null=True, related_name='courses', to='courses.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(default='Course', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course')),
                ('videos', models.ManyToManyField(null=True, related_name='videos', to='courses.video')),
            ],
        ),
    ]
