# Generated by Django 4.1.3 on 2022-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(default='Lorem ipsum', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='Lorem ipsum', max_length=600),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='Lorem ipsum', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='Lorem ipsum', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Lorem ipsum', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.CharField(default='Lorem ipsum', max_length=600),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default='Lorem ipsum', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.CharField(default='Lorem ipsum', max_length=400),
        ),
    ]
