# Generated by Django 4.1.3 on 2023-01-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.CharField(default='summary', max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
