# Generated by Django 4.1.3 on 2022-11-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_category_alter_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('courses', models.ManyToManyField(related_name='course', to='courses.course')),
            ],
        ),
    ]
