# Generated by Django 4.1.3 on 2023-01-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ManyToManyField(null=True, related_name='instructor', to='courses.instructor'),
        ),
    ]
