# Generated by Django 4.1.3 on 2022-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='courses.course'),
        ),
    ]
