# Generated by Django 4.1.3 on 2022-12-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_instructor_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='instructor',
            name='reviews',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='students',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='instructor',
            name='summary',
            field=models.CharField(default='Lorem ipsum', max_length=400),
        ),
    ]
