# Generated by Django 4.1.3 on 2023-01-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_id_chapter_courseid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='videoID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructorID',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='videos',
            field=models.ManyToManyField(null=True, related_name='videos', to='courses.video'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(null=True, related_name='courses', to='courses.instructor'),
        ),
    ]
