# Generated by Django 4.1.3 on 2022-12-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_chapters_instructor_rating_instructor_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.course'),
        ),
    ]
