# Generated by Django 4.1.3 on 2023-02-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_category_order_remove_chapter_videos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
