# Generated by Django 4.1.3 on 2022-12-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
