# Generated by Django 4.1.3 on 2022-12-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_chapter_video_delete_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='courses',
        ),
    ]
