# Generated by Django 4.1.3 on 2023-03-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_order_created_at_alter_order_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
