# Generated by Django 4.1.3 on 2022-12-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_instructor_remove_instructor_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(null=True, related_name='instructors', to='courses.instructor'),
        ),
    ]
